package db.hibernate.tables.isearch;

// Generated 2016-4-7 14:57:04 by Hibernate Tools 3.4.0.CR1

/**
 * AcaLogs generated by hbm2java
 */
public class AcaLogs implements java.io.Serializable {

	private Integer id;
	private String userid;
	private String query;
	private String title;
	private String authors;
	private String abstr;
	private String link;
	private Integer year;
	private Integer citecount;
	private String sources;
	private Double score;

	public AcaLogs() {
	}

	public AcaLogs(String userid, String query, String title, String authors,
			String abstr, String link, Integer year, Integer citecount,
			String sources, Double score) {
		this.userid = userid;
		this.query = query;
		this.title = title;
		this.authors = authors;
		this.abstr = abstr;
		this.link = link;
		this.year = year;
		this.citecount = citecount;
		this.sources = sources;
		this.score = score;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public String getAbstr() {
		return this.abstr;
	}

	public void setAbstr(String abstr) {
		this.abstr = abstr;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getCitecount() {
		return this.citecount;
	}

	public void setCitecount(Integer citecount) {
		this.citecount = citecount;
	}

	public String getSources() {
		return this.sources;
	}

	public void setSources(String sources) {
		this.sources = sources;
	}

	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

}
