package db.hibernate.tables.isearch;
// Generated 2015-12-14 17:29:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Areas generated by hbm2java
 */
@Entity
@Table(name = "areas", catalog = "isearch")
public class Areas implements java.io.Serializable {

	private Integer id;
	private String areaid;
	private String area;
	private String cityid;

	public Areas() {
	}

	public Areas(String areaid, String area, String cityid) {
		this.areaid = areaid;
		this.area = area;
		this.cityid = cityid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "areaid", nullable = false, length = 20)
	public String getAreaid() {
		return this.areaid;
	}

	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	@Column(name = "area", nullable = false, length = 50)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "cityid", nullable = false, length = 20)
	public String getCityid() {
		return this.cityid;
	}

	public void setCityid(String cityid) {
		this.cityid = cityid;
	}

}
