package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * Cities generated by hbm2java
 */
public class Cities implements java.io.Serializable {

	private Integer id;
	private String cityid;
	private String city;
	private String provinceid;

	public Cities() {
	}

	public Cities(String cityid, String city, String provinceid) {
		this.cityid = cityid;
		this.city = city;
		this.provinceid = provinceid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCityid() {
		return this.cityid;
	}

	public void setCityid(String cityid) {
		this.cityid = cityid;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvinceid() {
		return this.provinceid;
	}

	public void setProvinceid(String provinceid) {
		this.provinceid = provinceid;
	}

}
