package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * ClickResultSource generated by hbm2java
 */
public class ClickResultSource implements java.io.Serializable {

	private int userid;
	private Integer baiduCount;
	private Integer sogouCount;
	private Integer youdaoCount;
	private Integer bingCount;
	private Integer yahooCount;
	private String query;
	private String url;
	private String abstr;
	private Integer resultLocation;

	public ClickResultSource() {
	}

	public ClickResultSource(int userid) {
		this.userid = userid;
	}

	public ClickResultSource(int userid, Integer baiduCount,
			Integer sogouCount, Integer youdaoCount, Integer bingCount,
			Integer yahooCount, String query, String url, String abstr,
			Integer resultLocation) {
		this.userid = userid;
		this.baiduCount = baiduCount;
		this.sogouCount = sogouCount;
		this.youdaoCount = youdaoCount;
		this.bingCount = bingCount;
		this.yahooCount = yahooCount;
		this.query = query;
		this.url = url;
		this.abstr = abstr;
		this.resultLocation = resultLocation;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Integer getBaiduCount() {
		return this.baiduCount;
	}

	public void setBaiduCount(Integer baiduCount) {
		this.baiduCount = baiduCount;
	}

	public Integer getSogouCount() {
		return this.sogouCount;
	}

	public void setSogouCount(Integer sogouCount) {
		this.sogouCount = sogouCount;
	}

	public Integer getYoudaoCount() {
		return this.youdaoCount;
	}

	public void setYoudaoCount(Integer youdaoCount) {
		this.youdaoCount = youdaoCount;
	}

	public Integer getBingCount() {
		return this.bingCount;
	}

	public void setBingCount(Integer bingCount) {
		this.bingCount = bingCount;
	}

	public Integer getYahooCount() {
		return this.yahooCount;
	}

	public void setYahooCount(Integer yahooCount) {
		this.yahooCount = yahooCount;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAbstr() {
		return this.abstr;
	}

	public void setAbstr(String abstr) {
		this.abstr = abstr;
	}

	public Integer getResultLocation() {
		return this.resultLocation;
	}

	public void setResultLocation(Integer resultLocation) {
		this.resultLocation = resultLocation;
	}

}
