package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ClickLog generated by hbm2java
 */
public class ClickLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private Category category;
	private String query;
	private String url;
	private String classification;
	private Integer value;
	private Date date;
	private String title;
	private String abstr;
	private Integer rank;
	private Integer clickRank;

	public ClickLog() {
	}

	public ClickLog(User user, Category category, String query, String url,
			String classification, Integer value, Date date, String title,
			String abstr, Integer rank, Integer clickRank) {
		this.user = user;
		this.category = category;
		this.query = query;
		this.url = url;
		this.classification = classification;
		this.value = value;
		this.date = date;
		this.title = title;
		this.abstr = abstr;
		this.rank = rank;
		this.clickRank = clickRank;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAbstr() {
		return this.abstr;
	}

	public void setAbstr(String abstr) {
		this.abstr = abstr;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Integer getClickRank() {
		return this.clickRank;
	}

	public void setClickRank(Integer clickRank) {
		this.clickRank = clickRank;
	}

}
