package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * ClickSourcePreference generated by hbm2java
 */
public class ClickSourcePreference implements java.io.Serializable {

	private int userid;
	private Double baiduPreference;
	private Double sogouPreference;
	private Double youdaoPreference;
	private Double bingPreference;
	private Double yahooPreference;

	public ClickSourcePreference() {
	}

	public ClickSourcePreference(int userid) {
		this.userid = userid;
	}

	public ClickSourcePreference(int userid, Double baiduPreference,
			Double sogouPreference, Double youdaoPreference,
			Double bingPreference, Double yahooPreference) {
		this.userid = userid;
		this.baiduPreference = baiduPreference;
		this.sogouPreference = sogouPreference;
		this.youdaoPreference = youdaoPreference;
		this.bingPreference = bingPreference;
		this.yahooPreference = yahooPreference;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Double getBaiduPreference() {
		return this.baiduPreference;
	}

	public void setBaiduPreference(Double baiduPreference) {
		this.baiduPreference = baiduPreference;
	}

	public Double getSogouPreference() {
		return this.sogouPreference;
	}

	public void setSogouPreference(Double sogouPreference) {
		this.sogouPreference = sogouPreference;
	}

	public Double getYoudaoPreference() {
		return this.youdaoPreference;
	}

	public void setYoudaoPreference(Double youdaoPreference) {
		this.youdaoPreference = youdaoPreference;
	}

	public Double getBingPreference() {
		return this.bingPreference;
	}

	public void setBingPreference(Double bingPreference) {
		this.bingPreference = bingPreference;
	}

	public Double getYahooPreference() {
		return this.yahooPreference;
	}

	public void setYahooPreference(Double yahooPreference) {
		this.yahooPreference = yahooPreference;
	}

}
