package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer id;
	private Job job;
	private int addressId;
	private String companyName;

	public Company() {
	}

	public Company(Job job, int addressId, String companyName) {
		this.job = job;
		this.addressId = addressId;
		this.companyName = companyName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

}
