package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * GroupToCategory generated by hbm2java
 */
public class GroupToCategory implements java.io.Serializable {

	private Integer id;
	private GroupInfo groupInfo;
	private Category category;

	public GroupToCategory() {
	}

	public GroupToCategory(GroupInfo groupInfo, Category category) {
		this.groupInfo = groupInfo;
		this.category = category;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public GroupInfo getGroupInfo() {
		return this.groupInfo;
	}

	public void setGroupInfo(GroupInfo groupInfo) {
		this.groupInfo = groupInfo;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
