package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HotWords generated by hbm2java
 */
public class HotWords implements java.io.Serializable {

	private Integer hid;
	private String hotwords;
	private Date date;

	public HotWords() {
	}

	public HotWords(String hotwords, Date date) {
		this.hotwords = hotwords;
		this.date = date;
	}

	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	public String getHotwords() {
		return this.hotwords;
	}

	public void setHotwords(String hotwords) {
		this.hotwords = hotwords;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
