package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

	private int id;
	private String job;
	private Set<Company> companies = new HashSet<Company>(0);

	public Job() {
	}

	public Job(int id, String job) {
		this.id = id;
		this.job = job;
	}

	public Job(int id, String job, Set<Company> companies) {
		this.id = id;
		this.job = job;
		this.companies = companies;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
