package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * Provinces generated by hbm2java
 */
public class Provinces implements java.io.Serializable {

	private Integer id;
	private String provinceid;
	private String province;

	public Provinces() {
	}

	public Provinces(String provinceid, String province) {
		this.provinceid = provinceid;
		this.province = province;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProvinceid() {
		return this.provinceid;
	}

	public void setProvinceid(String provinceid) {
		this.provinceid = provinceid;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

}
