package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * QfgFeatures generated by hbm2java
 */
public class QfgFeatures implements java.io.Serializable {

	private Integer id;
	private Queries queriesByQueryFirst;
	private Queries queriesByQuerySecond;
	private String cookie;
	private Double edlevGt2;
	private Double charPov;
	private Double charSuf;
	private Double wordPov;
	private Double wordSuf;
	private Double commonWords;
	private Double wordJDistance;

	public QfgFeatures() {
	}

	public QfgFeatures(Queries queriesByQueryFirst,
			Queries queriesByQuerySecond, String cookie, Double edlevGt2,
			Double charPov, Double charSuf, Double wordPov, Double wordSuf,
			Double commonWords, Double wordJDistance) {
		this.queriesByQueryFirst = queriesByQueryFirst;
		this.queriesByQuerySecond = queriesByQuerySecond;
		this.cookie = cookie;
		this.edlevGt2 = edlevGt2;
		this.charPov = charPov;
		this.charSuf = charSuf;
		this.wordPov = wordPov;
		this.wordSuf = wordSuf;
		this.commonWords = commonWords;
		this.wordJDistance = wordJDistance;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Queries getQueriesByQueryFirst() {
		return this.queriesByQueryFirst;
	}

	public void setQueriesByQueryFirst(Queries queriesByQueryFirst) {
		this.queriesByQueryFirst = queriesByQueryFirst;
	}

	public Queries getQueriesByQuerySecond() {
		return this.queriesByQuerySecond;
	}

	public void setQueriesByQuerySecond(Queries queriesByQuerySecond) {
		this.queriesByQuerySecond = queriesByQuerySecond;
	}

	public String getCookie() {
		return this.cookie;
	}

	public void setCookie(String cookie) {
		this.cookie = cookie;
	}

	public Double getEdlevGt2() {
		return this.edlevGt2;
	}

	public void setEdlevGt2(Double edlevGt2) {
		this.edlevGt2 = edlevGt2;
	}

	public Double getCharPov() {
		return this.charPov;
	}

	public void setCharPov(Double charPov) {
		this.charPov = charPov;
	}

	public Double getCharSuf() {
		return this.charSuf;
	}

	public void setCharSuf(Double charSuf) {
		this.charSuf = charSuf;
	}

	public Double getWordPov() {
		return this.wordPov;
	}

	public void setWordPov(Double wordPov) {
		this.wordPov = wordPov;
	}

	public Double getWordSuf() {
		return this.wordSuf;
	}

	public void setWordSuf(Double wordSuf) {
		this.wordSuf = wordSuf;
	}

	public Double getCommonWords() {
		return this.commonWords;
	}

	public void setCommonWords(Double commonWords) {
		this.commonWords = commonWords;
	}

	public Double getWordJDistance() {
		return this.wordJDistance;
	}

	public void setWordJDistance(Double wordJDistance) {
		this.wordJDistance = wordJDistance;
	}

}
