package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Queries generated by hbm2java
 */
public class Queries implements java.io.Serializable {

	private Integer id;
	private String query;
	private Date date;
	private Set<QfgFeatures> qfgFeaturesesForQuerySecond = new HashSet<QfgFeatures>(
			0);
	private Set<QfgFeatures> qfgFeaturesesForQueryFirst = new HashSet<QfgFeatures>(
			0);

	public Queries() {
	}

	public Queries(String query, Date date,
			Set<QfgFeatures> qfgFeaturesesForQuerySecond,
			Set<QfgFeatures> qfgFeaturesesForQueryFirst) {
		this.query = query;
		this.date = date;
		this.qfgFeaturesesForQuerySecond = qfgFeaturesesForQuerySecond;
		this.qfgFeaturesesForQueryFirst = qfgFeaturesesForQueryFirst;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set<QfgFeatures> getQfgFeaturesesForQuerySecond() {
		return this.qfgFeaturesesForQuerySecond;
	}

	public void setQfgFeaturesesForQuerySecond(
			Set<QfgFeatures> qfgFeaturesesForQuerySecond) {
		this.qfgFeaturesesForQuerySecond = qfgFeaturesesForQuerySecond;
	}

	public Set<QfgFeatures> getQfgFeaturesesForQueryFirst() {
		return this.qfgFeaturesesForQueryFirst;
	}

	public void setQfgFeaturesesForQueryFirst(
			Set<QfgFeatures> qfgFeaturesesForQueryFirst) {
		this.qfgFeaturesesForQueryFirst = qfgFeaturesesForQueryFirst;
	}

}
