package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * UserSeSetting generated by hbm2java
 */
public class UserSeSetting implements java.io.Serializable {

	private Integer id;
	private User user;
	private String username;
	private String seSetting;

	public UserSeSetting() {
	}

	public UserSeSetting(User user, String username, String seSetting) {
		this.user = user;
		this.username = username;
		this.seSetting = seSetting;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSeSetting() {
		return this.seSetting;
	}

	public void setSeSetting(String seSetting) {
		this.seSetting = seSetting;
	}

}
