package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * UserCluster generated by hbm2java
 */
public class UserCluster implements java.io.Serializable {

	private Integer id;
	private User user;
	private int cid;

	public UserCluster() {
	}

	public UserCluster(User user, int cid) {
		this.user = user;
		this.cid = cid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

}
