package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserFavorWords generated by hbm2java
 */
public class UserFavorWords implements java.io.Serializable {

	private Integer wordid;
	private User user;
	private Category category;
	private String word;
	private String classification;
	private String relevance;
	private Date date;
	private double value;

	public UserFavorWords() {
	}

	public UserFavorWords(User user, String word, String classification,
			Date date, double value) {
		this.user = user;
		this.word = word;
		this.classification = classification;
		this.date = date;
		this.value = value;
	}

	public UserFavorWords(User user, Category category, String word,
			String classification, String relevance, Date date, double value) {
		this.user = user;
		this.category = category;
		this.word = word;
		this.classification = classification;
		this.relevance = relevance;
		this.date = date;
		this.value = value;
	}

	public Integer getWordid() {
		return this.wordid;
	}

	public void setWordid(Integer wordid) {
		this.wordid = wordid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public String getRelevance() {
		return this.relevance;
	}

	public void setRelevance(String relevance) {
		this.relevance = relevance;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
