package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String password;
	private String emailadress;
	private String imei;
	private String cookieid;
	private Set<UserFavorWords> userFavorWordses = new HashSet<UserFavorWords>(
			0);
	private Set<UserSeSetting> userSeSettings = new HashSet<UserSeSetting>(0);
	private Set<UserGroups> userGroupses = new HashSet<UserGroups>(0);
	private UserInfo userInfo;
	private Set<UserInterestValue> userInterestValues = new HashSet<UserInterestValue>(
			0);
	private Set<ClickLog> clickLogs = new HashSet<ClickLog>(0);
	private Set<UserCluster> userClusters = new HashSet<UserCluster>(0);

	public User() {
	}

	public User(String username, String password, String emailadress,
			String imei, String cookieid, Set<UserFavorWords> userFavorWordses,
			Set<UserSeSetting> userSeSettings, Set<UserGroups> userGroupses,
			UserInfo userInfo, Set<UserInterestValue> userInterestValues,
			Set<ClickLog> clickLogs, Set<UserCluster> userClusters) {
		this.username = username;
		this.password = password;
		this.emailadress = emailadress;
		this.imei = imei;
		this.cookieid = cookieid;
		this.userFavorWordses = userFavorWordses;
		this.userSeSettings = userSeSettings;
		this.userGroupses = userGroupses;
		this.userInfo = userInfo;
		this.userInterestValues = userInterestValues;
		this.clickLogs = clickLogs;
		this.userClusters = userClusters;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmailadress() {
		return this.emailadress;
	}

	public void setEmailadress(String emailadress) {
		this.emailadress = emailadress;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getCookieid() {
		return this.cookieid;
	}

	public void setCookieid(String cookieid) {
		this.cookieid = cookieid;
	}

	public Set<UserFavorWords> getUserFavorWordses() {
		return this.userFavorWordses;
	}

	public void setUserFavorWordses(Set<UserFavorWords> userFavorWordses) {
		this.userFavorWordses = userFavorWordses;
	}

	public Set<UserSeSetting> getUserSeSettings() {
		return this.userSeSettings;
	}

	public void setUserSeSettings(Set<UserSeSetting> userSeSettings) {
		this.userSeSettings = userSeSettings;
	}

	public Set<UserGroups> getUserGroupses() {
		return this.userGroupses;
	}

	public void setUserGroupses(Set<UserGroups> userGroupses) {
		this.userGroupses = userGroupses;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public Set<UserInterestValue> getUserInterestValues() {
		return this.userInterestValues;
	}

	public void setUserInterestValues(Set<UserInterestValue> userInterestValues) {
		this.userInterestValues = userInterestValues;
	}

	public Set<ClickLog> getClickLogs() {
		return this.clickLogs;
	}

	public void setClickLogs(Set<ClickLog> clickLogs) {
		this.clickLogs = clickLogs;
	}

	public Set<UserCluster> getUserClusters() {
		return this.userClusters;
	}

	public void setUserClusters(Set<UserCluster> userClusters) {
		this.userClusters = userClusters;
	}

}
