package db.hibernate.tables.isearch;

// Generated 2016-4-12 17:44:14 by Hibernate Tools 3.4.0.CR1

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private int userid;
	private User user;
	private String sex;
	private Integer age;
	private String home;
	private String address;
	private String job;
	private String company;
	private String interest;

	public UserInfo() {
	}

	public UserInfo(User user, String home, String address, String job,
			String company) {
		this.user = user;
		this.home = home;
		this.address = address;
		this.job = job;
		this.company = company;
	}

	public UserInfo(User user, String sex, Integer age, String home,
			String address, String job, String company, String interest) {
		this.user = user;
		this.sex = sex;
		this.age = age;
		this.home = home;
		this.address = address;
		this.job = job;
		this.company = company;
		this.interest = interest;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getHome() {
		return this.home;
	}

	public void setHome(String home) {
		this.home = home;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getInterest() {
		return this.interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

}
